### ISSUE TITLE
wrong values from oxford dataset

### ISSUE THREAD

**Issue by flesicek** [iERP-ai/businesswithcovid-generator#12]
Oxford dataset for majority of countries have a drop just 1-7 days before current date and due to missing data the risk score drops to 2.2 or 1.1.

![Screen Shot 2020-04-11 at 1 34 17 AM](https://user-images.githubusercontent.com/25140562/79029581-3fdccd00-7b95-11ea-9360-ddd37b0f3f34.jpg)
would it be possible before score forecasting & generation of the list of limitations to go backwards from current date and find first value which is higher than 2.3. replace rows till current date with that information? only after that generate table and current risk score etc.

**Comment by tommycarstensen** [comment]
@flesicek I'll probably do something else. I'll probably do a forward fill for each column in the dataframe; i.e. use the previous non-missing value. It is explained here:
https://stackoverflow.com/questions/27905295/how-to-replace-nans-by-preceding-values-in-pandas-dataframe

I'll do a visual inspection of the time series for each country afterwards.
